# name: Run Airdrop
on:
  workflow_dispatch:
jobs:
  airdrop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: pip install solana
      - name: Execute script
        env:
          VFB_PRIVATE_KEY: ${{ secrets.VFB_PRIVATE_KEY }}
        run: python vfb_airdrop.py
